apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tp-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: ton-image-frontend:latest   
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: tp-app

data:
  NODE_ENV: "production"
  PORT: "3000"